export class Config {
  static USEDEPOSIT = true; //TURN ON OR OFF DEPOSIT
  static DEPOSITAMOUNT = 0.00001; //DEPOSIT AMOUNT
  static DAILYDEPOSITCOUNT = 10; //DEPOSIT COUNT DAILY
  static GWEIPRICE = 0.15; //GWEI PRICE
  static WAITFORBLOCKCONFIRMATION = true; //IF TRUE AFTER TX EXECUTED BOT WILL WAIT TX TO BE MINED FIRST, IF FALSE AFTER TX EXECUTED BOT WILL CONTINUE TO NEXT TX
  static DISPLAY = "BLESS"; //TWIST or BLESS
}
